application:
  name: laravel-postgresql
  project: simple-example-laravel-with-postgresql
  organization: QoveryCommunity
databases:
- type: postgresql
  version: "12"
  name: my-db
- type: redis
  version: 6
  name: my-redis
routers:
- name: main
  routes:
  - application_name: laravel-postgresql
    paths:
    - /
